development:
  adapter: postgresql
  database: daiqpvung3athq
  host: ec2-23-21-219-12.compute-1.amazonaws.com
  port: 5432
  username: postgres
  password: Cc123456
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: daiqpvung3athq
  host: zengbo01.rnd.laxino.com
  port: 5432
  username: postgres
  password: Cc123456
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: daiqpvung3athq
  host: zengbo01.rnd.laxino.com
  port: 5432
  username: postgres
  password: Cc123456
  pool: 5
  timeout: 5000