development:
  adapter: postgresql
  database: bbs_development
  username: postgres
  password: Cc123456
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: bbs_test
  username: postgres
  password: Cc123456
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: bbs_production
  username: postgres
  password: Cc123456
  pool: 5
  timeout: 5000